### ISSUE TITLE
[Feature Request] Replying to repetitive committable code suggestions using threads

### ISSUE THREAD

**Issue by kkc-tonywu** [The-PR-Agent/pr-agent#920]
Hello everyone,

First of all, I'd like to express my gratitude to all those involved in integrating this tool with GitLab. So far, it has been working very well.

Whenever the PR-Agent conducts code reviews with commitable_code_suggestions enabled, it generates multiple suggestions. However, upon running the PR-Agent again, there is a chance of regenerating the same suggestions. Is it possible to respond to these repetitive suggestions through a threaded approach?

**Comment by mrT23** [comment]
1) i am not sure what is a "thread" in github (or in gitlab ? bitbucket ?). is that something that is supported ?

2) our recommended, and default way, for code suggestions is as a _single comment_. we introduced a lot of improvements there, including noise reduction, and are planning to keep working on that mode. commitable code suggestions are far too noisy for most users, and that's why we are not prioritizing them. Still, a contribution from the community will be welcomed

![image](https://github.com/Codium-ai/pr-agent/assets/21198860/e05c7a45-0943-4c12-9974-5bbcb6918203)

**Comment by kkc-tonywu** [comment]
I am referring to the GitLab platform. (Related API:  [Add note to existing merge request thread](https://docs.gitlab.com/ee/api/discussions.html#add-note-to-existing-merge-request-thread))

Because I noticed duplicated and similar code suggestions when using committable code suggestions, we would like to consolidate them under the same thread. This approach will help reduce clutter and streamline categorization.

![image](https://github.com/Codium-ai/pr-agent/assets/154858830/0f148533-be1a-433a-936c-6ee89a0cc4ce)

![image](https://github.com/Codium-ai/pr-agent/assets/154858830/9c380d04-bda3-41df-9102-3a9914753f4a)

>  commitable code suggestions are far too noisy for most users

I think there are two ways to solve this:

1. [[GITLAB] Aggregate review comments and shoot in 1 as generally the MR review works in Gitlab · Issue #307 · Codium-ai/pr-agent](https://github.com/Codium-ai/pr-agent/issues/307)
2. The notification settings can be adjusted and controlled through the configuration file, designed to be as flexible as possible.

**Comment by mrT23** [comment]
you are welcome to open a PR
